filebeat.prospectors:
- type: docker
  containers.ids:
  - '*'
  processors:
  - add_docker_metadata: {}
output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: 'elastic'
  password: 'changeme'
